-- 고객센터
CREATE TABLE NOTICE
(
    NO_NUM NUMBER NOT NULL,
    MEM_NUM NUMBER NOT NULL,
    NO_TITLE VARCHAR2(200) NOT NULL,
    NO_CONTENT CLOB NOT NULL,
    NO_REGDATE DATE DEFAULT SYSDATE,
    NO_MODIFYDATE DATE,
    NO_STATUS NUMBER(1) NOT NULL,
    NO_CATEGORY NUMBER(1),
    CONSTRAINT NOTICE_PK PRIMARY KEY (NO_NUM),
	CONSTRAINT NOTICE_FK1 FOREIGN KEY (MEM_NUM) REFERENCES MEMBER (MEM_NUM) ON DELETE CASCADE
);
CREATE SEQUENCE NOTICE_SEQ;



-- 챗봇
CREATE TABLE CHATBOT
(
    CROOM_NUM NUMBER NOT NULL,
    MEM_NUM NOT NULL,
    MEM_ID VARCHAR2(12),
    CROOM_REGDATE DATE DEFAULT SYSDATE,
    CONSTRAINT CHATBOT_PK PRIMARY KEY (CROOM_NUM),
    CONSTRAINT CHATBOT_FK FOREIGN KEY (MEM_NUM) REFERENCES MEMBER (MEM_NUM) ON DELETE CASCADE
);
CREATE SEQUENCE CHATBOT_SEQ;

CREATE TABLE CHATBOT_ROOM
(
    CROOM_NUM NUMBER NOT NULL,
    MEM_NUM NUMBER NOT NULL,
    MEM_ID VARCHAR2(12),
    CROOM_QUESTION VARCHAR2(500) NOT NULL,
    CROOM_ANSWER CLOB,
    CONSTRAINT CROOM_FK1 FOREIGN KEY (CROOM_NUM) REFERENCES CHATBOT (CROOM_NUM) ON DELETE CASCADE,
    CONSTRAINT CROOM_FK2 FOREIGN KEY (MEM_NUM) REFERENCES MEMBER (MEM_NUM) ON DELETE CASCADE
);

CREATE TABLE ANSWER
(
    AN_NUM NUMBER NOT NULL,
    AN_INTENT VARCHAR2(200) NOT NULL,
    AN_ANSWER CLOB,
    CONSTRAINT ANSWER_PK PRIMARY KEY (AN_NUM)
);
CREATE SEQUENCE ANSWER_SEQ;



-- 그룹 채팅
-- 채팅방
CREATE TABLE TALKROOM
(
    TALKROOM_NUM NUMBER,
    BASIC_NAME VARCHAR2(900) NOT NULL, --채팅 멤버를 추가할 때 채팅방 이름을 basic_name에서 가져다 씀
    TALKROOM_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT TALKROOM_PK PRIMARY KEY (TALKROOM_NUM)
);
CREATE SEQUENCE TALKROOM_SEQ;

--채팅멤버
CREATE TABLE TALK_MEMBER
(
    TALKROOM_NUM NUMBER NOT NULL,
    MEM_NUM NUMBER NOT NULL,
    ROOM_NAME VARCHAR2(900) NOT NULL,
    MEMBER_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT TALKMEMBER_FK1 FOREIGN KEY (TALKROOM_NUM) REFERENCES TALKROOM (TALKROOM_NUM) ON DELETE CASCADE,
    CONSTRAINT TALKMEMBER_FK2 FOREIGN KEY (MEM_NUM) REFERENCES MEMBER (MEM_NUM) ON DELETE CASCADE
);

-- 채팅 메시지
CREATE TABLE TALK
(
    TALK_NUM NUMBER,
    TALKROOM_NUM NUMBER NOT NULL, --수신그룹
    MEM_NUM NUMBER NOT NULL, --발신자
    MESSAGE VARCHAR2(4000) NOT NULL,
    CHAT_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT TALK_PK PRIMARY KEY (TALK_NUM),
    CONSTRAINT TALK_FK1 FOREIGN KEY (TALKROOM_NUM) REFERENCES TALKROOM (TALKROOM_NUM) ON DELETE CASCADE,
    CONSTRAINT TALK_FK2 FOREIGN KEY (MEM_NUM) REFERENCES MEMBER (MEM_NUM) ON DELETE CASCADE
);
CREATE SEQUENCE TALK_SEQ;

--메시지 읽음 체크
CREATE TABLE TALK_READ
(
    TALKROOM_NUM NUMBER NOT NULL,
    TALK_NUM NUMBER NOT NULL,
    MEM_NUM NUMBER NOT NULL,
    CONSTRAINT READ_FK1 FOREIGN KEY (TALKROOM_NUM) REFERENCES TALKROOM (TALKROOM_NUM) ON DELETE CASCADE,
    CONSTRAINT READ_FK2 FOREIGN KEY (TALK_NUM) REFERENCES TALK (TALK_NUM) ON DELETE CASCADE,
    CONSTRAINT READ_FK3 FOREIGN KEY (MEM_NUM) REFERENCES MEMBER (MEM_NUM) ON DELETE CASCADE
);



